version: '3.1'
services:
  common: &common
    image: bonk
    stdin_open: true
    volumes:
      - ./:/workspace
    working_dir: /workspace
  shell:
    <<: *common
    entrypoint: /bin/bash
  build:
    <<: *common
    entrypoint:
    - /bin/bash
    - -c
    - |
      mkdir build
      cd build
      i686-w64-mingw32-cmake .. -DCMAKE_CXX_FLAGS="-Wno-error=format-security"
      make -j $(nproc) install
  build-release:
    <<: *common
    entrypoint:
    - /bin/bash
    - -c
    - |
      mkdir build
      cd build
      i686-w64-mingw32-cmake .. -DCMAKE_CXX_FLAGS="-Wno-error=format-security" -DCMAKE_BUILD_TYPE=Release
      make -j $(nproc) install
  clean:
    <<: *common
    entrypoint:
    - /bin/bash
    - -c
    - |
      cd build
      make clean